const time = 100
const deleteTime = 10
const interval = 1000

new TypeIt("#Headline", {
    loop: true,
    cursorSpeed: 1000,
    speed: 100
})
    .type("2")
    .pause(time)
    .type("0")
    .pause(time)
    .type("2")
    .pause(time)
    .type("2")
    .pause(time * 2)
    .type("n")
    .pause(time)
    .type("i")
    .pause(time)
    .type("a")
    .pause(time)
    .type("n")
    .pause(deleteTime)
    .delete(4, { instant: true })
    .type("年")
    .pause(time * 2)
    .type(" ")
    .pause(time)
    .type("1")
    .pause(time)
    .type("0")
    .pause(time)
    .type("y")
    .pause(time * 2)
    .type("u")
    .pause(time)
    .type("e")
    .pause(deleteTime)
    .delete(3, { instant: true })
    .type("月")
    .pause(interval)
    .delete(null)
    .type("s")
    .pause(time)
    .type("h")
    .pause(time)
    .type("u")
    .pause(time)
    .type("o")
    .pause(time)
    .type("s")
    .pause(time)
    .type("h")
    .pause(time)
    .type("u")
    .pause(time)
    .type("o")
    .pause(deleteTime)
    .delete(8, { instant: true })
    .type("说说")
    .pause(time * 2)
    .type(" ")
    .pause(time)
    .type("w")
    .pause(time)
    .type("o")
    .pause(time)
    .type("h")
    .pause(time)
    .type("e")
    .pause(deleteTime)
    .delete(4, { instant: true })
    .type("我和")
    .pause(time * 2)
    .type("t")
    .pause(time)
    .type("o")
    .pause(time)
    .type("n")
    .pause(time)
    .type("g")
    .pause(time)
    .type("j")
    .pause(time)
    .type("i")
    .pause(time)
    .type("d")
    .pause(time)
    .type("e")
    .pause(deleteTime)
    .delete(8, { instant: true })
    .type("同济的")
    .pause(time * 2)
    .type("g")
    .pause(time)
    .type("u")
    .pause(time)
    .type("s")
    .pause(time)
    .type("h")
    .pause(time)
    .type("i")
    .pause(deleteTime)
    .delete(5, { instant: true })
    .type("故事")
    .pause(interval)
    .go();


