# Generated by Django 4.2.2 on 2023-06-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="V_blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("blog_img", models.ImageField(upload_to="", verbose_name="图片")),
                ("blog_content", models.TextField(verbose_name="博客内容")),
                ("blog_time", models.DateField(verbose_name="创建日期")),
                ("blog_creator", models.CharField(max_length=100, verbose_name="创建者")),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Like_creator", models.CharField(max_length=100, verbose_name="点赞者")),
                ("Like_time", models.DateField(verbose_name="点赞时间")),
                (
                    "Like_blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.v_blog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_creator",
                    models.CharField(max_length=100, verbose_name="评论者"),
                ),
                ("comment_content", models.TextField(verbose_name="留言")),
                ("comment_time", models.DateField(verbose_name="评论日期")),
                (
                    "comment_blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.v_blog"
                    ),
                ),
            ],
        ),
    ]
