# Generated by Django 4.2.2 on 2023-06-23 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_friend_alter_comment_comment_blog_delete_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="v_blog",
            name="blog_img",
            field=models.ImageField(upload_to="../media/blog_image", verbose_name="图片"),
        ),
        migrations.CreateModel(
            name="HEAD_img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Head_img",
                    models.ImageField(upload_to="../media/head_img", verbose_name="图片"),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="head_rel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
