# Generated by Django 4.2.2 on 2023-06-23 10:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0003_alter_v_blog_blog_img_head_img"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HEAD_img",
            new_name="H_img",
        ),
    ]
