# Generated by Django 4.2.2 on 2023-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_head_img_h_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="h_img",
            name="Head_img",
            field=models.ImageField(upload_to="media/head_img", verbose_name="图片"),
        ),
        migrations.AlterField(
            model_name="v_blog",
            name="blog_img",
            field=models.FileField(upload_to="media/img", verbose_name="图片"),
        ),
    ]
