# Generated by Django 4.2.2 on 2023-06-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_h_img_head_img_alter_v_blog_blog_img"),
    ]

    operations = [
        migrations.DeleteModel(
            name="H_img",
        ),
    ]
