# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/CPU_MIPS_54/CPU_MIPS_54.cache/wt [current_project]
set_property parent.project_path D:/CPU_MIPS_54/CPU_MIPS_54.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/CPU54_coe/mips_54_mars_simulate_student_ForWeb.coe
add_files D:/CPU54_coe/mips_54_mars_simulate_student.coe
add_files D:/CPU54_coe/mips_54_mars_board_switch_student.coe
add_files -quiet D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/new/ALU.v
  D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/new/Control.v
  D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/new/CLZ.v
  D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/new/HI_LO.v
  D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/new/DIV.v
  D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/new/MUL.v
  D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/new/CP0.v
  D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/new/Inst_Get.v
  D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/new/PC.v
  D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/new/regfile.v
  D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/new/cpu.v
  D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/new/DMEM.v
  D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/new/IMEM.v
  D:/CPU_MIPS_54/CPU_MIPS_54.srcs/sources_1/new/sccomp_dataflow.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
